#!/usr/bin/env python3

import collections
import json
import re
import sys
from pathlib import Path

import argh


def go(
    if_expression="True",
    process_expression="line",
    final_lines_expression="lines",
):
    in_lines = sys.stdin.readlines()  # in
    lines = list()  # out

    for line in in_lines:
        line = line.strip()
        if eval(if_expression):
            lines.append(eval(process_expression))

    lines = eval(final_lines_expression)

    for line in lines:
        print(line)


if __name__ == "__main__":
    argh.dispatch_command(go)
